/**
 * AetherFlow Curated Catalog
 * High-resolution video loops, 30+ community procedural canvas engines, and live 4K streams.
 * Bundled directly for instant offline capability, fast startup, and rich diversity.
 */

export const CURATED_CATALOG = [
  // ── High-Resolution Video Loops (Direct MP4 / 60FPS / Hardware MPV) ────────
  {
    id: 'cosmic-blackhole-singularity',
    name: 'Interstellar Black Hole Singularity',
    description: 'Cinematic 4K simulation of a gravitational vortex accretion disk with relativistic beaming.',
    author: 'CosmicVisions',
    authorPortfolio: 'https://unsplash.com/@vincentiu',
    license: 'CC BY-NC-ND 4.0',
    category: 'space',
    type: 'video',
    source: 'https://assets.mixkit.co/videos/42079/42079-720.mp4',
    preview: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1280&q=80',
    tags: ['space', 'cosmic', '4K', 'minimal', 'blackhole'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 28 * 1024 * 1024,
    mediaFormat: 'video/mp4',
    duration: 30,
    dimensions: '4K UHD',
    hasAudio: false,
    createdAt: '2026-09-18T10:00:00Z',
  },
  {
    id: 'cyberpunk-rainy-storefront',
    name: 'Neon Blade Runner Rain',
    description: 'Atmospheric rainy cyberpunk city storefront with flickering holographic signs and reflections.',
    author: 'NeoTokyoLab',
    authorPortfolio: 'https://unsplash.com/@alexpasarelu',
    license: 'CC BY-NC-ND 4.0',
    category: 'cyberpunk',
    type: 'video',
    source: 'https://assets.mixkit.co/videos/41668/41668-720.mp4',
    preview: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1280&q=80',
    tags: ['cyberpunk', 'city', 'rain', 'neon', '4K', 'anime'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 34 * 1024 * 1024,
    mediaFormat: 'video/mp4',
    duration: 24,
    dimensions: '4K UHD',
    hasAudio: false,
    createdAt: '2026-09-18T11:00:00Z',
  },
  {
    id: 'deep-bioluminescence-jellyfish',
    name: 'Abyssal Bioluminescent Jellyfish',
    description: 'Ethereal translucent jellyfish undulating rhythmically through deep glowing oceanic currents.',
    author: 'OceanicVibes',
    authorPortfolio: 'https://unsplash.com/@cristina_gottardi',
    license: 'CC BY-NC-ND 4.0',
    category: 'nature',
    type: 'video',
    source: 'https://assets.mixkit.co/videos/42823/42823-720.mp4',
    preview: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1280&q=80',
    tags: ['nature', 'ocean', 'peaceful', 'dark', '4K'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 31 * 1024 * 1024,
    mediaFormat: 'video/mp4',
    duration: 20,
    dimensions: '4K UHD',
    hasAudio: false,
    createdAt: '2026-09-18T12:00:00Z',
  },
  {
    id: 'retrowave-sunset-highway',
    name: 'Retro Wave Sunset Drive',
    description: 'Endless neon highway pursuit driving straight toward a pulsating wireframe synthetic sun.',
    author: 'SynthMaster84',
    authorPortfolio: 'https://unsplash.com/@danielkcheung',
    license: 'CC BY-NC-ND 4.0',
    category: 'retro',
    type: 'video',
    source: 'https://assets.mixkit.co/videos/41671/41671-720.mp4',
    preview: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1280&q=80',
    tags: ['retro', 'synthwave', 'neon', 'highway', 'sunset'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 22 * 1024 * 1024,
    mediaFormat: 'video/mp4',
    duration: 18,
    dimensions: '1080P FHD',
    hasAudio: false,
    createdAt: '2026-09-18T13:00:00Z',
  },
  {
    id: 'alpine-mountain-mist-dawn',
    name: 'Golden Hour Mountain Drifts',
    description: 'Sweeping aerial 4K drone cinematography soaring above misty jagged alpine mountain peaks.',
    author: 'AlpineDrone',
    authorPortfolio: 'https://unsplash.com/@kallu',
    license: 'CC BY-NC-ND 4.0',
    category: 'nature',
    type: 'video',
    source: 'https://assets.mixkit.co/videos/42220/42220-720.mp4',
    preview: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1280&q=80',
    tags: ['nature', 'mountain', 'drone', 'peaceful', '4K'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 45 * 1024 * 1024,
    mediaFormat: 'video/mp4',
    duration: 28,
    dimensions: '4K UHD',
    hasAudio: false,
    createdAt: '2026-09-18T14:00:00Z',
  },
  {
    id: 'matrix-cyber-terminal-stream',
    name: 'Matrix Cyber Infiltration',
    description: 'High-speed glowing green cryptographic terminal intrusion datastream with rolling hex blocks.',
    author: 'CipherGhost',
    authorPortfolio: 'https://unsplash.com/@markusspiske',
    license: 'CC BY-NC-ND 4.0',
    category: 'cyberpunk',
    type: 'video',
    source: 'https://assets.mixkit.co/videos/42080/42080-720.mp4',
    preview: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1280&q=80',
    tags: ['dark', 'hacker', 'green', 'cyberpunk', 'code'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 18 * 1024 * 1024,
    mediaFormat: 'video/mp4',
    duration: 16,
    dimensions: '1080P FHD',
    hasAudio: false,
    createdAt: '2026-09-18T15:00:00Z',
  },

  // ── Core Procedural Showcase Engines ─────────────────────────────────────────
  {
    id: 'engine-quantum-flux',
    name: 'Quantum Flux — Cyber Hex Matrix',
    description: 'Luminous cybernetic hexagonal matrix with interactive quantum energy pulses and particle sparks.',
    author: 'AetherFlow Core',
    authorPortfolio: '',
    license: 'Proprietary',
    category: 'cyberpunk',
    type: 'engine',
    engine: 'quantum-flux',
    source: 'engine:quantum-flux',
    preview: '/previews/quantum-flux.svg',
    tags: ['cyberpunk', 'interactive', 'neon', 'matrix', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    hasAudio: false,
    createdAt: '2026-09-19T10:00:00Z',
  },
  {
    id: 'engine-matrix-rain',
    name: 'Matrix Digital Code Rain',
    description: 'Classic green phosphor katakana digital rain with speed, density, and glyph customization.',
    author: 'AetherFlow Core',
    authorPortfolio: '',
    license: 'Proprietary',
    category: 'cyberpunk',
    type: 'engine',
    engine: 'matrix-rain',
    source: 'engine:matrix-rain',
    preview: '/previews/matrix-rain.svg',
    tags: ['dark', 'hacker', 'green', 'cyberpunk', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    hasAudio: false,
    createdAt: '2026-09-19T10:00:00Z',
  },
  {
    id: 'engine-cyber-particles',
    name: 'Cyber Particles Network',
    description: 'Connected particle constellation network with dynamic links and interactive cursor repulsion.',
    author: 'AetherFlow Core',
    authorPortfolio: '',
    license: 'Proprietary',
    category: 'abstract',
    type: 'engine',
    engine: 'cyber-particles',
    source: 'engine:cyber-particles',
    preview: '/previews/cyber-particles.svg',
    tags: ['dark', 'blue', 'network', 'interactive', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    hasAudio: false,
    createdAt: '2026-09-19T10:00:00Z',
  },
  {
    id: 'engine-synthwave-grid',
    name: 'Synthwave Neon Horizon Grid',
    description: 'Retro 80s perspective grid with glowing neon horizon and scanline atmosphere.',
    author: 'AetherFlow Core',
    authorPortfolio: '',
    license: 'Proprietary',
    category: 'retro',
    type: 'engine',
    engine: 'synthwave-grid',
    source: 'engine:synthwave-grid',
    preview: '/previews/synthwave-grid.svg',
    tags: ['retro', 'purple', 'neon', 'synthwave', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    hasAudio: false,
    createdAt: '2026-09-19T10:00:00Z',
  },

  // ── 30 Curated Community Procedural Canvas Engines ───────────────────────────
  // 1. Space
  {
    id: 'comm-engine-stellar-warp',
    name: 'Stellar Warp — Hyperspace Jump',
    description: 'Relativistic star warp flying outward from center with lightspeed streak vectors.',
    author: 'AstroProcedural',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'space',
    type: 'engine',
    engine: 'stellar-warp',
    source: 'engine:stellar-warp',
    preview: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1280&q=80',
    tags: ['space', 'stars', 'warp', 'fast', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-black-hole-lens',
    name: 'Singularity — Gravitational Lensing',
    description: 'Supermassive black hole accretion disk with Doppler beaming and event horizon absorption.',
    author: 'RelativityLab',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'space',
    type: 'engine',
    engine: 'black-hole-lens',
    source: 'engine:black-hole-lens',
    preview: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1280&q=80',
    tags: ['space', 'cosmic', 'gravity', 'dark', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-supernova-burst',
    name: 'Supernova Remnant Shockwave',
    description: 'Expanding interstellar gas shockwave with pulsing stardust particle dispersal.',
    author: 'NebulaCrafter',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'space',
    type: 'engine',
    engine: 'supernova-burst',
    source: 'engine:supernova-burst',
    preview: 'https://images.unsplash.com/photo-1543722530-d2c3201371e7?w=1280&q=80',
    tags: ['space', 'nebula', 'burst', 'vibrant', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-orbital-mechanics',
    name: 'Keplerian Orbital Dynamics',
    description: 'Harmonious planetary orbits revolving with luminous Keplerian elliptical trails.',
    author: 'CelestialMath',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'space',
    type: 'engine',
    engine: 'orbital-mechanics',
    source: 'engine:orbital-mechanics',
    preview: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=1280&q=80',
    tags: ['space', 'planets', 'minimal', 'solar', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-solar-flare',
    name: 'Helios Solar Flare Corona',
    description: 'Turbulent convective solar plasma surface with twisting magnetic prominence loops.',
    author: 'SolarSpectra',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'space',
    type: 'engine',
    engine: 'solar-flare',
    source: 'engine:solar-flare',
    preview: 'https://images.unsplash.com/photo-1532693322450-2cb5c511067d?w=1280&q=80',
    tags: ['space', 'sun', 'fire', 'orange', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },

  // 2. Cyberpunk & Sci-Fi
  {
    id: 'comm-engine-cyber-hex-circuit',
    name: 'Cyber Hex PCB Circuit',
    description: 'Electric data pulses racing through motherboards and cybernetic circuit tracks.',
    author: 'ZeroOneDev',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'cyberpunk',
    type: 'engine',
    engine: 'cyber-hex-circuit',
    source: 'engine:cyber-hex-circuit',
    preview: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1280&q=80',
    tags: ['cyberpunk', 'circuit', 'tech', 'blue', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-neon-wireframe-tunnel',
    name: 'Infinite Wireframe Tunnel 3D',
    description: 'Perspective 3D geometric tunnel cruising forward into infinite neon darkness.',
    author: 'RetroGridBoy',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'cyberpunk',
    type: 'engine',
    engine: 'neon-wireframe-tunnel',
    source: 'engine:neon-wireframe-tunnel',
    preview: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1280&q=80',
    tags: ['cyberpunk', 'retro', 'tunnel', '3d', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-quantum-entanglement',
    name: 'Quantum Entanglement Resonance',
    description: 'Dynamic entangled quantum states exchanging oscillating resonance laser beams.',
    author: 'QuantumWave',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'cyberpunk',
    type: 'engine',
    engine: 'quantum-entanglement',
    source: 'engine:quantum-entanglement',
    preview: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1280&q=80',
    tags: ['cyberpunk', 'quantum', 'physics', 'interactive', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-holographic-clock',
    name: 'Holographic Chrono HUD',
    description: 'Futuristic circular telemetry HUD with rotating arc gauges and digital clock readout.',
    author: 'HUDDesignStudio',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'cyberpunk',
    type: 'engine',
    engine: 'holographic-clock',
    source: 'engine:holographic-clock',
    preview: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=1280&q=80',
    tags: ['cyberpunk', 'hud', 'clock', 'minimal', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-sonar-radar-sweep',
    name: 'Tactical Sonar Radar Sweep',
    description: 'Naval military green phosphor radar sweep with range rings and fading sonar blips.',
    author: 'SonarOps',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'cyberpunk',
    type: 'engine',
    engine: 'sonar-radar-sweep',
    source: 'engine:sonar-radar-sweep',
    preview: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1280&q=80',
    tags: ['cyberpunk', 'military', 'radar', 'green', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-neural-synapse',
    name: 'Neural Synaptic Cortex',
    description: 'Deep neural graph with branching dendrites and electrical action potential spikes.',
    author: 'SynapseAI',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'cyberpunk',
    type: 'engine',
    engine: 'neural-synapse',
    source: 'engine:neural-synapse',
    preview: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=1280&q=80',
    tags: ['cyberpunk', 'ai', 'neural', 'purple', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },

  // 3. Anime & Nature
  {
    id: 'comm-engine-sakura-fall',
    name: 'Sakura Blossom Wind Drift',
    description: 'Serene Japanese anime cherry blossom petals tumbling gently over an evening sky.',
    author: 'SakuraDreamer',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'anime',
    type: 'engine',
    engine: 'sakura-fall',
    source: 'engine:sakura-fall',
    preview: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1280&q=80',
    tags: ['anime', 'nature', 'sakura', 'pink', 'peaceful', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-autumn-leaves',
    name: 'Autumn Maple Flutter',
    description: 'Warm crimson and golden leaves tumbling through crisp morning autumn wind.',
    author: 'KomorebiArt',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'nature',
    type: 'engine',
    engine: 'autumn-leaves',
    source: 'engine:autumn-leaves',
    preview: 'https://images.unsplash.com/photo-1507371341162-763b5e419408?w=1280&q=80',
    tags: ['nature', 'autumn', 'leaves', 'warm', 'cozy', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-firefly-forest',
    name: 'Enchanted Firefly Sanctuary',
    description: 'Gentle bioluminescent fireflies pulsating softly in a twilight enchanted forest.',
    author: 'DeepWoods',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'nature',
    type: 'engine',
    engine: 'firefly-forest',
    source: 'engine:firefly-forest',
    preview: 'https://images.unsplash.com/photo-1511497584788-87676104235f?w=1280&q=80',
    tags: ['nature', 'forest', 'fireflies', 'calm', 'night', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-rainy-window',
    name: 'Cozy Rainy Window Pane',
    description: 'Gentle condensation with dripping rain streaks and colorful warm city street bokeh.',
    author: 'LofiCafe',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'lofi',
    type: 'engine',
    engine: 'rainy-window',
    source: 'engine:rainy-window',
    preview: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=1280&q=80',
    tags: ['nature', 'lofi', 'rain', 'cozy', 'chill', 'anime', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-gentle-snowfall',
    name: 'Whispering Winter Snowfall',
    description: 'Multi-depth parallax snowfall drifting with gentle winter atmospheric turbulence.',
    author: 'NordicFrost',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'nature',
    type: 'engine',
    engine: 'gentle-snowfall',
    source: 'engine:gentle-snowfall',
    preview: 'https://images.unsplash.com/photo-1517299321609-52687d1bc55a?w=1280&q=80',
    tags: ['nature', 'winter', 'snow', 'minimal', 'white', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-ocean-waves',
    name: 'Moonlit Tidal Ocean Swells',
    description: 'Translucent ocean waves with crest foam undulating smoothly beneath moonlight.',
    author: 'CoastlineAudio',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'nature',
    type: 'engine',
    engine: 'ocean-waves',
    source: 'engine:ocean-waves',
    preview: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1280&q=80',
    tags: ['nature', 'ocean', 'waves', 'blue', 'peaceful', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-thunderstorm-lightning',
    name: 'Midnight Thunderstorm Bolts',
    description: 'Dark storm clouds with rolling ambient flashes and sudden branching lightning.',
    author: 'StormWatcher',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'nature',
    type: 'engine',
    engine: 'thunderstorm-lightning',
    source: 'engine:thunderstorm-lightning',
    preview: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=1280&q=80',
    tags: ['nature', 'storm', 'lightning', 'dark', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },

  // 4. Abstract & Generative Math
  {
    id: 'comm-engine-hypnotic-spiral',
    name: 'Hypnotic Archimedes Vortex',
    description: 'Infinite logarithmic optical vortex with continuous neon gradient phase cycles.',
    author: 'OpticalFlow',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'abstract',
    type: 'engine',
    engine: 'hypnotic-spiral',
    source: 'engine:hypnotic-spiral',
    preview: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1280&q=80',
    tags: ['abstract', 'spiral', 'psychedelic', 'purple', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-voronoi-cells',
    name: 'Living Voronoi Tessellation',
    description: 'Dynamic stained-glass cellular diagram with gentle organic seed relaxation.',
    author: 'GenerativeLab',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'abstract',
    type: 'engine',
    engine: 'voronoi-cells',
    source: 'engine:voronoi-cells',
    preview: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1280&q=80',
    tags: ['abstract', 'geometric', 'voronoi', 'minimal', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-plasma-waves',
    name: 'Demoscene Liquid Plasma',
    description: 'Vibrant multi-sine liquid plasma with shimmering psychedelic color spectrums.',
    author: 'DemosceneClassic',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'abstract',
    type: 'engine',
    engine: 'plasma-waves',
    source: 'engine:plasma-waves',
    preview: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=1280&q=80',
    tags: ['abstract', 'plasma', 'retro', 'color', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-flow-field',
    name: 'Curl Noise Silk Flow Field',
    description: 'Hundreds of luminous micro-particles tracing silky vector currents across dark canvas.',
    author: 'PerlinPoet',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'abstract',
    type: 'engine',
    engine: 'flow-field',
    source: 'engine:flow-field',
    preview: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1280&q=80',
    tags: ['abstract', 'flow', 'particles', 'smooth', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-lissajous-knots',
    name: 'Lissajous Harmonograph Knots',
    description: 'Continuous 3D harmonic knot geometries forming intricate luminous yarn ribbons.',
    author: 'MathSculptor',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'abstract',
    type: 'engine',
    engine: 'lissajous-knots',
    source: 'engine:lissajous-knots',
    preview: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=1280&q=80',
    tags: ['abstract', 'math', 'curves', 'gold', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-chladni-resonance',
    name: 'Chladni Cymatics Sand Mandala',
    description: 'Acoustic sand particle nodal lines shifting dynamically between harmonic frequencies.',
    author: 'CymaticVibe',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'abstract',
    type: 'engine',
    engine: 'chladni-resonance',
    source: 'engine:chladni-resonance',
    preview: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1280&q=80',
    tags: ['abstract', 'cymatics', 'geometry', 'green', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },

  // 5. Retro & Chill & Gaming
  {
    id: 'comm-engine-cassette-tape',
    name: 'Outrun 80s Cassette Deck',
    description: 'Transparent 80s cassette with rotating spool teeth, magnetic tape, and synth waveform.',
    author: 'CassetteRevival',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'retro',
    type: 'engine',
    engine: 'cassette-tape',
    source: 'engine:cassette-tape',
    preview: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1280&q=80',
    tags: ['retro', 'lofi', 'synthwave', '80s', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-isometric-city',
    name: 'Isometric Neon Metropolis',
    description: 'Minimalist 3D isometric cyber skyscrapers with glowing office windows and rooftop beacons.',
    author: 'PixelArchitect',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'city',
    type: 'engine',
    engine: 'isometric-city',
    source: 'engine:isometric-city',
    preview: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1280&q=80',
    tags: ['retro', 'city', 'cyberpunk', 'isometric', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-neon-equalizer',
    name: 'Radial Neon Audio Equalizer',
    description: '360-degree radial music frequency visualizer bars with energetic beat oscillation.',
    author: 'AuraSpectrum',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'retro',
    type: 'engine',
    engine: 'neon-equalizer',
    source: 'engine:neon-equalizer',
    preview: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1280&q=80',
    tags: ['retro', 'audio', 'music', 'visualizer', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-pixel-star-night',
    name: '8-Bit Retro Moon & Stars',
    description: 'Nostalgic 8-bit pixel art night sky with blocky pixel moon and twinkling stars.',
    author: 'ChiptuneDream',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'gaming',
    type: 'engine',
    engine: 'pixel-star-night',
    source: 'engine:pixel-star-night',
    preview: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1280&q=80',
    tags: ['gaming', 'retro', 'pixel', 'stars', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-matrix-hex-code',
    name: 'Hex Memory Dump Column',
    description: 'Phosphor green and cyan hexadecimal memory addresses cascading in computer terminal style.',
    author: 'CyberKernel',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'minimal',
    type: 'engine',
    engine: 'matrix-hex-code',
    source: 'engine:matrix-hex-code',
    preview: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1280&q=80',
    tags: ['cyberpunk', 'matrix', 'code', 'minimal', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },
  {
    id: 'comm-engine-sunset-coastal-drive',
    name: 'Sunset Coastal Synth Horizon',
    description: 'Low-poly vector synthwave ocean swells reflecting a giant striped twilight sun.',
    author: 'MiamiDrive82',
    authorPortfolio: 'https://unsplash.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'retro',
    type: 'engine',
    engine: 'sunset-coastal-drive',
    source: 'engine:sunset-coastal-drive',
    preview: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1280&q=80',
    tags: ['retro', 'synthwave', 'sunset', 'anime', 'procedural'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: 'Vector 60FPS',
    createdAt: '2026-09-20T00:00:00Z',
  },

  // ── Verified 4K Live Streams & Ambient YouTube Feeds ────────────────────────
  {
    id: 'iss-earth-orbit-4k',
    name: 'Earth from Space — NASA ISS 4K Live',
    description: 'Real-time high-definition views of planet Earth from the International Space Station.',
    author: 'NASA Live',
    authorPortfolio: 'https://www.nasa.gov',
    license: 'Public Domain',
    category: 'space',
    type: 'youtube',
    source: 'https://www.youtube.com/watch?v=DDU-rZs-Ic4',
    preview: 'https://img.youtube.com/vi/DDU-rZs-Ic4/hqdefault.jpg',
    tags: ['space', 'earth', '4K', 'live', 'nasa'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: '4K UHD',
    hasAudio: false,
    createdAt: '2026-09-19T12:00:00Z',
  },
  {
    id: 'shinjuku-rainy-walk-4k',
    name: 'Rainy Night in Tokyo Shinjuku 4K',
    description: 'Ultra-HD 4K ambient rainy stroll through Shinjuku and Akihabara neon streets.',
    author: 'TokyoBinaural',
    authorPortfolio: 'https://youtube.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'city',
    type: 'youtube',
    source: 'https://www.youtube.com/watch?v=eZe4Q_58UTU',
    preview: 'https://img.youtube.com/vi/eZe4Q_58UTU/hqdefault.jpg',
    tags: ['city', 'tokyo', 'rain', 'night', '4K', 'anime'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: '4K UHD',
    hasAudio: true,
    createdAt: '2026-09-19T13:00:00Z',
  },
  {
    id: 'blade-runner-ambient-4k',
    name: 'Cyberpunk 2077 Night City 4K Ambience',
    description: 'Atmospheric dystopian skyline with floating spinners, holographic billboards, and gentle fog.',
    author: 'CyberAmbience',
    authorPortfolio: 'https://youtube.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'cyberpunk',
    type: 'youtube',
    source: 'https://www.youtube.com/watch?v=sPU238_Wc1E',
    preview: 'https://img.youtube.com/vi/sPU238_Wc1E/hqdefault.jpg',
    tags: ['cyberpunk', 'city', 'dark', '4K', 'neon', 'anime'],
    downloads: 0,
    likes: 0,
    featured: true,
    fileSize: 0,
    dimensions: '4K UHD',
    hasAudio: true,
    createdAt: '2026-09-19T14:00:00Z',
  },
  {
    id: 'deep-forest-rain-thunder-4k',
    name: 'Ancient Rainforest Rain & Thunder 4K',
    description: 'Lush green mossy canopy with gentle cascading rain and calming ambient soundscape.',
    author: 'NatureSoundscapes',
    authorPortfolio: 'https://youtube.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'nature',
    type: 'youtube',
    source: 'https://www.youtube.com/watch?v=mPZkdNFkNps',
    preview: 'https://img.youtube.com/vi/mPZkdNFkNps/hqdefault.jpg',
    tags: ['nature', 'rain', 'forest', 'peaceful', '4K'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: '4K UHD',
    hasAudio: true,
    createdAt: '2026-09-19T15:00:00Z',
  },
  {
    id: 'interstellar-gargantua-ambient',
    name: 'Interstellar Deep Space Journey 4K',
    description: 'Slow hypnotic drift across cosmic star clusters and relativistic gravitational lensing.',
    author: 'CosmoAmbience',
    authorPortfolio: 'https://youtube.com',
    license: 'CC BY-NC-ND 4.0',
    category: 'space',
    type: 'youtube',
    source: 'https://www.youtube.com/watch?v=Yf1eSg5q9v4',
    preview: 'https://img.youtube.com/vi/Yf1eSg5q9v4/hqdefault.jpg',
    tags: ['space', 'minimal', 'stars', '4K', 'ambient'],
    downloads: 0,
    likes: 0,
    featured: false,
    fileSize: 0,
    dimensions: '4K UHD',
    hasAudio: true,
    createdAt: '2026-09-19T16:00:00Z',
  },
]
